version: "3"
services:
    go-revel:
        build: etc/revel
        ports:
            - 9010:9000
        volumes:
            - .:/go/src/MyApp
        links:
            - db
    db:
        image: mysql:5.6
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: MyDB
            MYSQL_USER: MyDB
            MYSQL_PASSWORD: mydbpassword
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - MysqlVolume:/var/lib/mysql

volumes:
  MysqlVolume: